version: 0.2

env:
  variables:
    AWS_REGION: 'us-east-1'
    GLUE_BUCKET: 'insightflow-wistia'
    GLUE_SCRIPT_PATH: 'glue-scripts'

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Running pre-build"
      # - |
      #   echo "Get list of changed files..."
      #   CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null||git diff --name-only HEAD)
      #   echo "Changed files: $CHANGED_FILES"
  build:
    commands:
      - echo "Starting deployment"
      - |
        echo "Deploying all Lambdas and Glue scripts..."
        
        cd Close/lambdas
        zip close-receiver.zip close-receiver.py
        aws lambda update-function-code --function-name close-receiver --zip-file fileb://close-receiver.zip --region $AWS_REGION
        zip close-enricher.zip close-enricher.py
        aws lambda update-function-code --function-name close-enricher --zip-file fileb://close-enricher.zip --region $AWS_REGION
        zip close-notifier-loader.zip close-notifier-loader.py
        aws lambda update-function-code --function-name close-notifier-loader --zip-file fileb://close-notifier-loader.zip --region $AWS_REGION
        cd ../../
        
        cd Calendly/lambdas
        zip calendly-receiver.zip calendly-receiver.py
        aws lambda update-function-code --function-name calendly-receiver --zip-file fileb://calendly-receiver.zip --region $AWS_REGION
        zip calendly-enricher.zip calendly-enricher.py
        aws lambda update-function-code --function-name calendly-enricher --zip-file fileb://calendly-enricher.zip --region $AWS_REGION
        cd ../../
        
        aws s3 cp Wistia/glue/wistia-ingest.py s3://$GLUE_BUCKET/$GLUE_SCRIPT_PATH/wistia-ingestion.py
        aws s3 cp Wistia/glue/wistia-silver-transformation.py s3://$GLUE_BUCKET/$GLUE_SCRIPT_PATH/wistia-silver-transformation.py
        aws s3 cp Wistia/glue/wistia-gold.py s3://$GLUE_BUCKET/$GLUE_SCRIPT_PATH/wistia-gold.py
  post_build:
    commands:
      - echo "Deployment complete"